import type {
  MetricDelta,
  MetricSemantics,
  ChangeClassification,
  MetricAvailability,
} from './types.ts';

export function safeDivide(
  numerator: number | null | undefined,
  denominator: number | null | undefined,
  fallback: number | null = null,
): number | null {
  if (
    numerator === null ||
    numerator === undefined ||
    isNaN(numerator) ||
    denominator === null ||
    denominator === undefined ||
    isNaN(denominator) ||
    denominator === 0
  ) {
    return fallback;
  }
  const val = numerator / denominator;
  return isFinite(val) ? val : fallback;
}

export function classifyChange(
  percentageDelta: number | null,
  thresholds = { strong: 15, mild: 3 },
): ChangeClassification {
  if (percentageDelta === null || isNaN(percentageDelta)) {
    return 'STABLE';
  }
  if (percentageDelta >= thresholds.strong) return 'STRONG_INCREASE';
  if (percentageDelta >= thresholds.mild) return 'INCREASE';
  if (percentageDelta <= -thresholds.strong) return 'STRONG_DECREASE';
  if (percentageDelta <= -thresholds.mild) return 'DECREASE';
  return 'STABLE';
}

export function computeMetricDelta(
  current: number,
  comparison: number | null,
  semantics: MetricSemantics = 'POSITIVE_WHEN_HIGHER',
  availability: MetricAvailability = 'SUPPORTED',
): MetricDelta {
  if (comparison === null || isNaN(comparison)) {
    return {
      current,
      comparison: null,
      absoluteDelta: null,
      percentageDelta: null,
      classification: 'STABLE',
      direction: 'NONE',
      isFavorable: null,
      availability,
    };
  }

  const absoluteDelta = current - comparison;
  const percentageDelta =
    comparison > 0 ? (absoluteDelta / comparison) * 100 : null;

  const classification = classifyChange(percentageDelta);

  let direction: 'UP' | 'DOWN' | 'FLAT' | 'NONE' = 'FLAT';
  if (absoluteDelta > 0) direction = 'UP';
  else if (absoluteDelta < 0) direction = 'DOWN';

  let isFavorable: boolean | null = null;
  if (direction === 'UP') {
    isFavorable = semantics === 'POSITIVE_WHEN_HIGHER';
  } else if (direction === 'DOWN') {
    isFavorable = semantics === 'POSITIVE_WHEN_LOWER';
  }

  return {
    current,
    comparison,
    absoluteDelta,
    percentageDelta:
      percentageDelta !== null && isFinite(percentageDelta)
        ? Math.round(percentageDelta * 10) / 10
        : null,
    classification,
    direction,
    isFavorable,
    availability,
  };
}

export type MetricMetadata = {
  key: string;
  label: string;
  description: string;
  formula: string;
  source: string;
  semantics: MetricSemantics;
  availability: MetricAvailability;
};

export const METRIC_DEFINITIONS: Record<string, MetricMetadata> = {
  gmv: {
    key: 'gmv',
    label: 'Affiliate GMV',
    description: 'Total Gross Merchandise Value generated by affiliate creators in selected period.',
    formula: 'Sum of GMV across all matching order items.',
    source: 'Marketplace payment order export rows (net of refunds for Shopee per BQ-01 deferral).',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  orders: {
    key: 'orders',
    label: 'Total Orders',
    description: 'Count of validated orders attributed to affiliate links or creator tags.',
    formula: 'Sum of orders across all records.',
    source: 'Marketplace payment order export rows.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  units: {
    key: 'units',
    label: 'Units Sold (Quantity)',
    description: 'Total quantity of individual product units sold through affiliates.',
    formula: 'Sum of units_sold across all records.',
    source: 'Marketplace payment order export rows.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  affiliatesWithSales: {
    key: 'affiliatesWithSales',
    label: 'Affiliates with Sales',
    description: 'Distinct count of affiliate creators who generated 1 or more orders in the period.',
    formula: 'Count of unique creator/account IDs with orders > 0.',
    source: 'Affiliate account mappings in performance rows.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  activeAffiliates: {
    key: 'activeAffiliates',
    label: 'Total Active Creators',
    description: 'Count of all creators registered with activity in the workspace.',
    formula: 'Count of distinct creators associated with accounts.',
    source: 'Workspace account registries.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  commission: {
    key: 'commission',
    label: 'Affiliate Commission',
    description: 'Total commission amount accrued or paid to affiliate creators.',
    formula: 'Sum of commission across all records.',
    source: 'Marketplace commission fields in daily rows.',
    semantics: 'POSITIVE_WHEN_LOWER',
    availability: 'SUPPORTED',
  },
  asp: {
    key: 'asp',
    label: 'Average Selling Price (ASP)',
    description: 'Average GMV generated per unit sold.',
    formula: 'GMV / Units Sold.',
    source: 'Calculated from canonical GMV and Units Sold.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  aov: {
    key: 'aov',
    label: 'Average Order Value (AOV / ABS)',
    description: 'Average GMV generated per order.',
    formula: 'GMV / Orders.',
    source: 'Calculated from canonical GMV and Orders.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  roi: {
    key: 'roi',
    label: 'Return on Investment (ROI)',
    description: 'Multiple of GMV generated relative to affiliate commission spend.',
    formula: 'GMV / Commission.',
    source: 'Calculated from canonical GMV and Commission.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  costRatio: {
    key: 'costRatio',
    label: 'Commission Cost Ratio',
    description: 'Percentage of GMV spent on affiliate commission.',
    formula: '(Commission / GMV) * 100.',
    source: 'Calculated from canonical Commission and GMV.',
    semantics: 'POSITIVE_WHEN_LOWER',
    availability: 'SUPPORTED',
  },
  clicks: {
    key: 'clicks',
    label: 'Product Clicks',
    description: 'Total referral link clicks (Shopee-specific).',
    formula: 'Sum of clicks.',
    source: 'Shopee payment order export.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  conversionRate: {
    key: 'conversionRate',
    label: 'Click-to-Order Conversion Rate',
    description: 'Percentage of referral clicks converting into completed orders.',
    formula: '(Orders / Clicks) * 100.',
    source: 'Shopee performance data.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'PARTIALLY_SUPPORTED',
  },
  videoCount: {
    key: 'videoCount',
    label: 'Published Videos',
    description: 'Number of creator videos tagging affiliate products (TikTok-specific).',
    formula: 'Sum of video_count.',
    source: 'TikTok performance export.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  liveCount: {
    key: 'liveCount',
    label: 'Livestream Sessions',
    description: 'Number of affiliate creator live selling sessions (TikTok-specific).',
    formula: 'Sum of live_count.',
    source: 'TikTok performance export.',
    semantics: 'POSITIVE_WHEN_HIGHER',
    availability: 'SUPPORTED',
  },
  refundRate: {
    key: 'refundRate',
    label: 'Refund / Return Rate',
    description: 'Estimated refund or cancellation rate. Note: BQ-01 remains deferred by user.',
    formula: 'Refunded GMV / Gross GMV.',
    source: 'Marketplace refund reports (supplemental analysis only).',
    semantics: 'POSITIVE_WHEN_LOWER',
    availability: 'BUSINESS_CONFIRMATION_REQUIRED',
  },
};
