import type { WorkspaceData, RecordData } from '../../types/domain.ts';
import { records, thresholds } from '../operations/config.ts';
import { getWorkspaceDataCoverage } from '../imports/automation.ts';

export type Priority='P0'|'P1'|'P2'|'P3';
export type ActionStatus='OPEN'|'IN_PROGRESS'|'SNOOZED'|'RESOLVED'|'DISMISSED';
export type OperationalAction={id:string;rule_id:string;category:string;title:string;reason:string;recommended_action:string;priority:Priority;severity:'Critical'|'High'|'Medium'|'Low';marketplace?:string;entity_type?:string;entity_id?:string;deduplication_key:string;status:ActionStatus;evidence:Record<string,unknown>;due_at?:string;generated_at:string;last_detected_at:string;assigned_to?:string|null;started_at?:string|null;snoozed_until?:string|null;resolved_at?:string|null;resolution_note?:string|null;source_task_id?:string|null};

const day=86400000;
const iso=(d:Date)=>d.toISOString().slice(0,10);
const add=(date:string,n:number)=>iso(new Date(new Date(date+'T00:00:00Z').getTime()+n*day));
const days=(a:string,b:string)=>Math.floor((new Date(b+'T00:00:00Z').getTime()-new Date(a+'T00:00:00Z').getTime())/day);
const uuidFor=(key:string)=>{let h=2166136261;for(const c of key)h=Math.imul(h^c.charCodeAt(0),16777619);const x=(h>>>0).toString(16).padStart(8,'0');return `${x}-0000-4000-8000-${x}${x.slice(0,4)}`};

function names(data:WorkspaceData,id?:string){return data.entities.creators.find(x=>x.id===id)?.name||data.entities.products.find(x=>x.id===id)?.name||data.entities.campaigns.find(x=>x.id===id)?.name||'Workspace item';}
function action(rule:string,category:string,title:string,reason:string,next:string,priority:Priority,key:string,now:string,extra:Partial<OperationalAction>={}):OperationalAction{return {id:uuidFor(key),rule_id:rule,category,title,reason,recommended_action:next,priority,severity:priority==='P0'?'Critical':priority==='P1'?'High':priority==='P2'?'Medium':'Low',deduplication_key:key,status:'OPEN',evidence:{},generated_at:now+'T00:00:00Z',last_detected_at:now+'T00:00:00Z',...extra};}

export function generateOperationalActions(data:WorkspaceData,asOf=new Date()):OperationalAction[]{
 const now=iso(asOf),t=thresholds(data),out:OperationalAction[]=[];
 for(const task of data.entities.tasks.filter(x=>x.status!=='Done'&&x.due_date)){const due=String(task.due_date),over=due<now;if(over||due===now)out.push(action(over?'TASK_OVERDUE':'TASK_DUE_TODAY','Tasks',over?'Overdue task':'Task due today',`${task.name} is ${over?Math.max(1,days(due,now))+' day(s) overdue':'due today'}.`,'Complete the task or update its due date.',over?'P1':'P2',`task:${task.id}`,now,{entity_type:'tasks',entity_id:task.id,due_at:due+'T17:00:00+07:00',evidence:{dueDate:due,priority:task.priority}}));}
 for(const row of records(data,'creator_outreach')){if(!row.contacted_at||['Replied','Interested','Converted','Declined'].includes(String(row.status)))continue;const age=days(String(row.contacted_at),now),creator=names(data,String(row.creator_id));const milestone=age>=t.no_response_days?t.no_response_days:age>=t.second_follow_up_days?t.second_follow_up_days:age>=t.first_follow_up_days?t.first_follow_up_days:0;if(milestone)out.push(action(`OUTREACH_H${milestone}`,'Outreach',milestone===t.no_response_days?'No-response review due':`H+${milestone} follow-up due`,`${creator} was contacted ${age} day(s) ago and has not progressed.`,milestone===t.no_response_days?'Decide whether to close or schedule a later re-approach.':'Send a manual follow-up and record the response.','P2',`outreach:${row.id}:h${milestone}`,now,{entity_type:'creator_outreach',entity_id:row.id,due_at:add(String(row.contacted_at),milestone)+'T09:00:00+07:00',evidence:{contactedAt:row.contacted_at,daysSinceContact:age,status:row.status}}));}
 const latestStock=new Map<string,RecordData>();for(const s of records(data,'product_stock_snapshots').sort((a,b)=>String(a.snapshot_at).localeCompare(String(b.snapshot_at))))latestStock.set(String(s.product_id),s);
 for(const s of latestStock.values()){const qty=Number(s.stock_quantity),critical=qty<=t.critical_stock,low=qty<=t.low_stock;if(!low)continue;const assignments=records(data,'hsl_creator_products').filter(x=>x.product_id===s.product_id),hero=assignments.some(x=>x.priority==='Hero');const active=assignments.map(x=>records(data,'hsl_activations').find(h=>h.id===x.hsl_activation_id)).filter(h=>h&&['Confirmed','Ready','Active'].includes(String(h.status)));const p:Priority=critical&&active.length?'P0':critical||hero?'P1':'P2';out.push(action(active.length?'HSL_STOCK_RISK':critical?'CRITICAL_STOCK':'LOW_STOCK','Stock',active.length?'Stock risk affecting HSL creator':critical?'Critical stock':'Low stock',`${names(data,String(s.product_id))} has ${qty} units in the latest ${s.marketplace} snapshot${active.length?` and affects ${active.length} HSL activation(s)`:''}.`,'Coordinate replenishment or assign a replacement SKU with StoreOps.',p,`stock:${s.product_id}:${s.marketplace}`,now,{marketplace:String(s.marketplace),entity_type:'products',entity_id:String(s.product_id),evidence:{stockQuantity:qty,snapshotAt:s.snapshot_at,heroSku:hero,hslActivationCount:active.length}}));}
 for(const h of records(data,'hsl_activations').filter(x=>['Confirmed','Ready','Active'].includes(String(x.status)))){const assigned=records(data,'hsl_creator_products').filter(x=>x.hsl_activation_id===h.id);if(!assigned.some(x=>x.priority==='Hero'))out.push(action('HSL_MISSING_HERO_SKU','HSL','HSL creator missing hero SKU',`${names(data,String(h.creator_id))} has an active HSL plan without a hero SKU assignment.`,'Review creator performance and assign the most suitable hero SKU.','P1',`hsl:${h.id}:hero`,now,{entity_type:'hsl_activations',entity_id:h.id,evidence:{startDate:h.start_date,status:h.status}}));}
 for(const s of records(data,'sample_seedings')){const creator=names(data,String(s.creator_id));if(s.status==='Shipped'&&s.shipped_at&&days(String(s.shipped_at),now)>t.sample_days)out.push(action('SAMPLE_RECEIPT_OVERDUE','Samples','Sample receipt overdue',`${creator}'s sample was shipped ${days(String(s.shipped_at),now)} day(s) ago and is not recorded as received.`,'Check delivery status and update the sample record.','P2',`sample:${s.id}:receipt`,now,{entity_type:'sample_seedings',entity_id:s.id,evidence:{shippedAt:s.shipped_at,status:s.status}}));if(['Received','Activation Pending'].includes(String(s.status))&&s.received_at&&days(String(s.received_at),now)>t.sample_days)out.push(action('SAMPLE_ACTIVATION_OVERDUE','Samples','Received sample has no activation',`${creator} received the sample ${days(String(s.received_at),now)} day(s) ago without recorded activation.`,'Confirm the deliverable plan and activation date.','P2',`sample:${s.id}:activation`,now,{entity_type:'sample_seedings',entity_id:s.id,evidence:{receivedAt:s.received_at,status:s.status}}));}
 for(const p of records(data,'peak_days').filter(x=>String(x.event_date)>=now&&days(now,String(x.event_date))<=t.peak_day_warning_days)){const members=records(data,'peak_day_creators').filter(x=>x.peak_day_id===p.id),confirmed=members.filter(x=>['Confirmed','Completed'].includes(String(x.status))).length,target=Number(p.target_creators||0),missing=Math.max(0,target-confirmed),lead=days(now,String(p.event_date));if(missing||!p.strategy){const pr:Priority=lead<=1?'P0':lead<=3?'P1':'P2';out.push(action('PEAK_DAY_READINESS','Peak Day','Peak Day readiness gap',`${p.name} is T-${lead}. ${missing} creator lock(s) remain${p.strategy?'':'; strategy is not ready'}.`,'Lock the remaining creators and complete the missing readiness components.',pr,`peak:${p.id}:readiness`,now,{entity_type:'peak_days',entity_id:p.id,due_at:String(p.event_date)+'T00:00:00+07:00',evidence:{eventDate:p.event_date,daysRemaining:lead,targetCreators:target,confirmedCreators:confirmed,strategyReady:Boolean(p.strategy)}}));}}
 for(const market of ['Shopee', 'TikTok'] as const) {
  const cov = getWorkspaceDataCoverage(data, market, now);
  if (!cov.isH2Ready) {
    out.push(action(`DATA_COVERAGE_${market.toUpperCase()}_MISSING`, 'Data Coverage', `${market} H-2 data missing`, `${market} data coverage is behind by ${cov.missingDaysCount} day(s). Target cutoff for H-2 reporting is ${cov.h2CutoffDate}.`, `Export and import the latest ${market} payment order report in Import Center.`, 'P1', `coverage:${market.toLowerCase()}:${now}`, now, { marketplace: market, evidence: { marketplace: market, coverageEnd: cov.coverageEnd, h2CutoffDate: cov.h2CutoffDate, missingDaysCount: cov.missingDaysCount, isH2Ready: false } }));
  }
 }
 const perf=[...data.tiktok_performance.map(x=>({...x,marketplace:'TikTok',creator_id:data.tiktok_accounts.find(a=>a.id===x.account_id)?.creator_id})),...data.shopee_performance.map(x=>({...x,marketplace:'Shopee',creator_id:data.shopee_accounts.find(a=>a.id===x.account_id)?.creator_id}))];
 for(const c of data.entities.creators){const rows=perf.filter(x=>x.creator_id===c.id),recent=rows.filter(x=>x.date>=add(now,-6)&&x.date<=now),previous=rows.filter(x=>x.date>=add(now,-13)&&x.date<=add(now,-7)),r=recent.reduce((s,x)=>s+x.gmv,0),b=previous.reduce((s,x)=>s+x.gmv,0),salesDays=new Set(recent.filter(x=>x.gmv>0).map(x=>x.date)).size,last=rows.map(x=>x.date).sort().at(-1);if(b>=t.minimum_baseline_gmv&&salesDays>=t.minimum_sales_days){const change=(r-b)/b*100;if(change<=-t.performance_decline_threshold)out.push(action('CREATOR_GMV_DECLINE','Creator','Creator GMV declining',`${c.name} generated ${Math.round(r).toLocaleString('en-US')} in the last 7 days, ${Math.abs(change).toFixed(1)}% below the previous 7 days.`,'Review product, stock, content, and activation issues with the creator.','P1',`creator:${c.id}:decline`,now,{entity_type:'creators',entity_id:c.id,evidence:{comparison:'Last 7 days vs previous 7 days',recentGmv:r,baselineGmv:b,changePercent:change,salesDays}}));else if(change>=t.performance_spike_threshold)out.push(action('CREATOR_GMV_SPIKE','Creator','Creator performance spike',`${c.name} grew ${change.toFixed(1)}% in the last 7 days with ${salesDays} sales day(s).`,'Review the drivers and consider additional SKU or campaign support.','P3',`creator:${c.id}:spike`,now,{entity_type:'creators',entity_id:c.id,evidence:{comparison:'Last 7 days vs previous 7 days',recentGmv:r,baselineGmv:b,changePercent:change,salesDays}}));}if(last&&days(last,now)>=t.reactivation_days&&!records(data,'creator_outreach').some(x=>x.creator_id===c.id&&['No Response','Follow Up','Replied','Interested'].includes(String(x.status))))out.push(action('CREATOR_REACTIVATION','Creator','Reactivation opportunity',`${c.name} previously generated sales but has been inactive for ${days(last,now)} day(s).`,'Review the creator and start outreach if still relevant.','P3',`creator:${c.id}:reactivation`,now,{entity_type:'creators',entity_id:c.id,evidence:{lastSaleDate:last,inactiveDays:days(last,now)}}));}
 const weekday=new Intl.DateTimeFormat('en-US',{weekday:'long',timeZone:'Asia/Jakarta'}).format(asOf),week=Math.ceil(Number(now.slice(8,10))/7);for(const r of records(data,'recurring_task_templates')){const due=(r.recurrence_type==='Weekly'&&r.weekly_day===weekday)||(r.recurrence_type==='Monthly'&&Number(r.monthly_week)===week);if(due)out.push(action('WEEKLY_OPERATING_RHYTHM','Reports','Operating checklist due',`${r.name} is scheduled for ${weekday}${r.recurrence_type==='Monthly'?`, week ${week}`:''}.`,'Complete the checklist item or create a task from this action.','P2',`rhythm:${r.id}:${now}`,now,{entity_type:'recurring_task_templates',entity_id:r.id,due_at:now+'T17:00:00+07:00',evidence:{recurrence:r.recurrence_type,weekday,weekOfMonth:week}}));}
 return out.sort((a,b)=>a.priority.localeCompare(b.priority)||String(a.due_at||'9999').localeCompare(String(b.due_at||'9999'))||a.title.localeCompare(b.title));
}

export function mergePersistedActions(generated:OperationalAction[],persisted:RecordData[],now=new Date()):OperationalAction[]{const current=now.toISOString();return generated.map(g=>{const p=persisted.find(x=>x.deduplication_key===g.deduplication_key);if(!p)return g as OperationalAction;const status=p.status==='SNOOZED'&&p.snoozed_until&&String(p.snoozed_until)<=current?'OPEN':String(p.status) as ActionStatus;return {...g,...p,status,evidence:g.evidence,last_detected_at:g.last_detected_at} as OperationalAction;}).concat(persisted.filter(p=>!generated.some(g=>g.deduplication_key===p.deduplication_key)).map(p=>p as unknown as OperationalAction)).sort((a,b)=>a.priority.localeCompare(b.priority)||String(a.due_at||'9999').localeCompare(String(b.due_at||'9999')));}
