import { config as entityConfig } from '../data/config.ts';
import type { Role, RecordData, WorkspaceData } from '../../types/domain.ts';
export type OpField = { key: string; label: string; type?: 'text'|'number'|'date'|'textarea'|'email'; options?: string[]; relation?: string; required?: boolean; min?: number; max?: number };
export type OpConfig = { title: string; singular: string; fields: OpField[]; columns: string[]; immutable?: boolean };
const f = (key:string,label:string,extra:Partial<OpField>={}):OpField => ({key,label,...extra});
const rel = (key:string,label:string,relation:string,required=true)=>f(key,label,{relation,required});
const choice = (key:string,label:string,options:string[])=>f(key,label,{options,required:true});
const date = (key:string,label:string,required=false)=>f(key,label,{type:'date',required});
const num = (key:string,label:string)=>f(key,label,{type:'number'});
const notes = (key='notes',label='Notes')=>f(key,label,{type:'textarea'});
export const acquisitionStages = ['Prospect','Contacted','Responded','Interested','Locked','Activated','Affiliate With Sales'];
export const activationStages = ['Target','Contacted','Negotiating','Locked','Ready','Active','Completed','Declined'];
export const sampleStages = ['Proposed','Approved','Preparing','Shipped','Received','Activation Pending','Activated','Generated Sales'];
export const operationConfig:Record<string,OpConfig> = {
  creator_outreach:{title:'Outreach',singular:'Outreach',fields:[rel('creator_id','Creator','creators'),rel('campaign_id','Campaign','campaigns',false),choice('channel','Channel',['WhatsApp','Email','Phone','Other']),f('reason','Reason',{required:true}),rel('template_id','Template','outreach_templates',false),date('contacted_at','Contacted on'),choice('status','Response',['No Response','Replied','Interested','Declined','Follow Up','Converted']),date('follow_up_at','Follow up on'),notes()],columns:['creator_id','reason','channel','contacted_at','follow_up_at','status']},
  outreach_templates:{title:'Message templates',singular:'Template',fields:[f('name','Template name',{required:true}),choice('marketplace','Marketplace',['Shopee','TikTok','Multi-platform']),f('activation_type','Activation type'),notes('message','Message · {creator_name}, {campaign_name}, {brand_name}, {product_name}, {peak_day}')],columns:['name','marketplace','activation_type']},
  creator_acquisition_events:{title:'Acquisition history',singular:'Stage event',immutable:true,fields:[rel('creator_id','Creator','creators'),choice('status','Stage',acquisitionStages),f('source','Source'),notes()],columns:['creator_id','status','source','created_at']},
  hsl_activations:{title:'HSL control center',singular:'HSL activation',fields:[rel('creator_id','Creator','creators'),rel('campaign_id','Campaign','campaigns'),rel('shopee_account_id','Shopee account','shopee_accounts'),choice('status','Status',['Candidate','Contacted','Confirmed','Ready','Active','Paused','Completed']),date('start_date','Start date',true),date('end_date','End date',true),notes('strategy_notes','Activation strategy'),notes('performance_notes','Performance notes')],columns:['creator_id','campaign_id','status','start_date','end_date']},
  hsl_creator_products:{title:'SKU assignments',singular:'SKU assignment',fields:[rel('hsl_activation_id','HSL activation','hsl_activations'),rel('product_id','Product','products'),choice('priority','Priority',['Hero','Primary','Secondary','Test']),notes('reason','Assignment reason'),notes()],columns:['hsl_activation_id','product_id','priority','reason']},
  product_stock_snapshots:{title:'Stock watch',singular:'Stock update',immutable:true,fields:[rel('product_id','Product','products'),choice('marketplace','Marketplace',['Shopee','TikTok']),f('stock_quantity','Stock quantity',{type:'number',required:true}),date('snapshot_at','Snapshot date',true),choice('source','Source',['Manual','Import']),notes()],columns:['product_id','marketplace','stock_quantity','snapshot_at','source']},
  sample_seedings:{title:'Sample seeding',singular:'Sample',fields:[rel('creator_id','Creator','creators'),rel('campaign_id','Campaign','campaigns',false),rel('product_id','Product','products'),choice('purpose','Purpose',['Live','Video','Campaign','Product Launch','Testing']),choice('status','Status',sampleStages),date('requested_at','Requested on',true),date('approved_at','Approved on'),date('shipped_at','Shipped on'),date('received_at','Received on'),date('expected_activation_at','Expected activation'),date('activated_at','Activated on'),f('tracking_number','Tracking number'),notes()],columns:['creator_id','product_id','campaign_id','status','expected_activation_at','tracking_number']},
  peak_days:{title:'Peak Days',singular:'Peak Day',fields:[f('name','Event name',{required:true}),f('event_type','Event type',{required:true}),rel('campaign_id','Campaign','campaigns'),date('event_date','Event date',true),num('target_gmv','Target GMV'),num('target_creators','Creator target'),num('target_live_creators','Live creator target'),num('target_video_creators','Video creator target'),notes('strategy','Strategy'),choice('status','Status',['Planning','Ready','Active','Completed'])],columns:['name','event_type','event_date','campaign_id','target_creators','status']},
  peak_day_creators:{title:'Peak Day creators',singular:'Peak Day creator',fields:[rel('peak_day_id','Peak Day','peak_days'),rel('creator_id','Creator','creators'),choice('format','Format',['Live','Video','Both']),choice('status','Schedule',['Unconfirmed','Confirmed','Completed'])],columns:['peak_day_id','creator_id','format','status']},
  campaign_creators:{title:'Creator activation',singular:'Campaign creator',fields:[rel('campaign_id','Campaign','campaigns'),rel('creator_id','Creator','creators'),choice('status','Activation status',activationStages),choice('format','Format',['Live','Video','Both']),date('scheduled_at','Scheduled date'),notes()],columns:['creator_id','campaign_id','format','status','locked_at','locked_by']},
  monthly_plans:{title:'Monthly planning',singular:'Monthly plan',fields:[f('name','Plan name',{required:true}),date('month','Month beginning',true),notes('objectives','Objectives'),notes('planned_campaigns','Planned campaigns'),notes('peak_days','Peak Days'),num('target_creators','Creator target'),notes('product_focus','Product focus'),notes('hero_skus','Hero SKUs'),notes('strategy','Activation strategy'),notes('risks','Risks'),notes()],columns:['name','month','target_creators','objectives']},
  recurring_task_templates:{title:'Recurring work',singular:'Work template',fields:[f('name','Task title',{required:true}),choice('recurrence_type','Recurrence',['Weekly','Monthly','Campaign event']),f('weekly_day','Weekday',{options:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']}),f('monthly_week','Week of month',{type:'number',min:1,max:5}),f('relative_campaign_event','Relative campaign event'),rel('campaign_id','Campaign','campaigns',false),f('owner','Assignee'),notes()],columns:['name','recurrence_type','weekly_day','monthly_week','owner']},
  reports:{title:'Reporting workspace',singular:'Report',fields:[f('name','Report name',{required:true}),choice('report_type','Report type',['Internal Weekly','Haleon Weekly','Monthly Recap','Campaign Report']),choice('marketplace','Marketplace',['Shopee','TikTok','Multi-platform']),rel('client_id','Client','clients',false),rel('campaign_id','Campaign','campaigns',false),date('period_start','Period start',true),date('period_end','Period end',true),date('cutoff_date','Data cutoff',true),notes('what_went_well','What went well'),notes('issues','Issues'),notes('next_action','Next action')],columns:['name','report_type','marketplace','period_start','cutoff_date','status']},
  report_snapshots:{title:'Report snapshots',singular:'Snapshot',immutable:true,fields:[rel('report_id','Report','reports'),notes('snapshot_json','Frozen metrics')],columns:['report_id','created_at']},
  metric_targets:{title:'Metric targets',singular:'Metric target',fields:[rel('client_id','Client','clients',false),rel('brand_id','Brand','brands',false),rel('campaign_id','Campaign','campaigns',false),choice('marketplace','Marketplace',['Shopee','TikTok','Multi-platform']),choice('metric','Metric',['Affiliate GMV','Affiliates With Sales','Orders','Units Sold']),date('period_start','Period start',true),date('period_end','Period end',true),f('target_value','Target value',{type:'number',required:true,min:0})],columns:['metric','marketplace','period_start','period_end','target_value']},
  workspace_preferences:{title:'Operational thresholds',singular:'Threshold settings',fields:[f('name','Settings name',{required:true}),f('growth_threshold','Growing above (%)',{type:'number',min:0}),f('decline_threshold','Declining below (%)',{type:'number',min:-100,max:0}),f('critical_threshold','Critical below (%)',{type:'number',min:-100,max:0}),num('inactivity_days','Inactivity days'),num('low_stock','Low stock at or below'),num('critical_stock','Critical stock at or below'),num('sample_days','Days after receipt before alert'),num('cutoff_days','Reporting cutoff lag (days)'),num('performance_decline_threshold','Performance decline (%)'),num('minimum_baseline_gmv','Minimum baseline GMV'),num('performance_spike_threshold','Performance spike (%)'),num('minimum_sales_days','Minimum sales days'),num('hsl_upcoming_days','HSL upcoming window'),num('first_follow_up_days','First follow-up days'),num('second_follow_up_days','Second follow-up days'),num('no_response_days','No-response days'),num('reactivation_days','Reactivation days'),num('peak_day_warning_days','Peak Day warning window')],columns:['name','performance_decline_threshold','inactivity_days','low_stock','critical_stock','sample_days','peak_day_warning_days']},
  operational_alerts:{title:'Alert history',singular:'Alert',fields:[f('alert_type','Type'),f('entity_type','Entity'),f('entity_id','Record ID'),f('message','Message'),choice('severity','Severity',['Info','Warning','Critical']),date('resolved_at','Resolved date')],columns:['alert_type','severity','message','resolved_at']},
  business_rules:{title:'Business rules',singular:'Business rule',immutable:true,fields:[],columns:['rule_key','name','marketplace','scope_type','version','status']},
  operational_actions:{title:'Action Center',singular:'Action',immutable:true,fields:[],columns:['priority','title','category','due_at','status']},
  brand_mappings:{title:'Brand mappings',singular:'Brand mapping',fields:[rel('product_id','Product','products'),rel('brand_id','Brand','brands'),choice('status','Status',['mapped','unmapped','ambiguous'])],columns:['product_id','brand_id','status']},
  report_datasets:{title:'Report datasets',singular:'Report dataset',immutable:true,fields:[rel('report_id','Report','reports'),f('dataset_schema_version','Schema version')],columns:['report_id','dataset_schema_version','created_at']},
  integration_connections:{title:'Integrations',singular:'Integration connection',fields:[f('provider','Provider'),f('marketplace','Marketplace'),f('status','Status')],columns:['provider','marketplace','status','last_sync_at']},
  integration_sync_runs:{title:'Automated sync runs',singular:'Sync run',immutable:true,fields:[f('provider','Provider'),f('capability','Capability'),f('status','Status')],columns:['provider','capability','status','created_at']},
  communication_templates:{title:'Message templates',singular:'Communication template',fields:[f('name','Template name',{required:true}),choice('category','Category',['FIRST_OUTREACH','FOLLOW_UP_1','FOLLOW_UP_2','NO_RESPONSE','REAPPROACH','INTERESTED','SAMPLE_FOLLOW_UP','HSL','CAMPAIGN_INVITE','CUSTOM']),choice('channel','Channel',['WHATSAPP','INSTAGRAM_DM','TIKTOK_DM','EMAIL','OTHER']),choice('marketplace','Marketplace',['Shopee','TikTok','Multi-platform']),rel('campaign_id','Campaign','campaigns',false),rel('client_id','Client','clients',false),notes('body','Message body · use {{creator_name}}, {{campaign_name}}, {{brand_name}}, {{marketplace}}, {{product_name}}, {{deadline}}')],columns:['name','category','channel','marketplace','current_version']},
  communication_events:{title:'Communication log',singular:'Communication event',immutable:true,fields:[rel('creator_id','Creator','creators'),choice('channel','Channel',['WHATSAPP','INSTAGRAM_DM','TIKTOK_DM','EMAIL','OTHER']),choice('event_type','Event type',['CONTACTED','RESPONDED','FOLLOW_UP','NOTE','PREPARATION']),date('contacted_at','Contacted date'),f('actor','Actor'),notes('note','Notes')],columns:['creator_id','channel','event_type','contacted_at','actor']},
};
operationConfig.tasks={...entityConfig.tasks,fields:entityConfig.tasks.fields};
export const operationTables = Object.keys(operationConfig).filter(t=>t!=='tasks');
export function records(data:WorkspaceData,table:string):RecordData[] {
  if(table in data.entities) return data.entities[table as keyof typeof data.entities];
  if(table==='campaign_creators') return data.campaign_creators.map(r=>({name:'Campaign creator',status:'Target',created_at:'',...r}));
  if(table==='shopee_accounts'||table==='tiktok_accounts') return data[table].map(r=>({name:r.username,created_at:'',...r}));
  return data.operations?.[table] || [];
}
export function canOperate(role:Role, table:string){
  if(['business_rules','operational_actions'].includes(table)) return false;
  if(role==='Admin') return true;
  if(table==='workspace_preferences') return false;
  if(['reports','report_snapshots'].includes(table)) return role==='Analyst'||role==='Affiliate Manager';
  return role==='Affiliate Manager';
}
export const defaultThresholds={growth_threshold:10,decline_threshold:-10,critical_threshold:-30,inactivity_days:14,low_stock:30,critical_stock:10,sample_days:7,cutoff_days:2,performance_decline_threshold:30,minimum_baseline_gmv:1000000,performance_spike_threshold:50,minimum_sales_days:2,hsl_upcoming_days:2,first_follow_up_days:3,second_follow_up_days:7,no_response_days:14,reactivation_days:30,peak_day_warning_days:7};
export function thresholds(data:WorkspaceData){
  const r=records(data,'workspace_preferences')[0];
  return Object.fromEntries(Object.entries(defaultThresholds).map(([k,v])=>[k,r?.[k]===null||r?.[k]===undefined?v:Number(r[k])])) as typeof defaultThresholds;
}
