export type RawRow = Record<string, string>;
export type ImportIssue = { row:number; field:string; sourceValue:string; severity:'WARNING'|'ERROR'; message:string; suggestedAction:string };
export type CanonicalRow = { source_row_number?:number; date:string; order_id:string; username:string; campaign_id:string; product_id:string; source_product_id:string; source_item_id:string; gmv:number; orders:number; units_sold:number; commission:number; video_count?:number; live_count?:number; clicks?:number; conversion_rate?:number };
export const normalizedHeader=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
export function detectColumns(headers:string[],aliases:Record<string,string[]>){const normalized=new Map(headers.map(h=>[normalizedHeader(h),h]));return Object.fromEntries(Object.entries(aliases).map(([key,names])=>[key,names.map(normalizedHeader).map(name=>normalized.get(name)).find(Boolean)||'']));}
export const readMapped=(row:RawRow,mapping:Record<string,string>,key:string)=>(mapping[key]?String(row[mapping[key]]??'').trim():'');
export function parseNumber(value:string){const raw=value.replace(/\s/g,'').replace(/^Rp/i,'');if(!raw)return 0;const normalized=raw.includes(',')&&raw.includes('.')?(raw.lastIndexOf(',')>raw.lastIndexOf('.')?raw.replaceAll('.','').replace(',','.'):raw.replaceAll(',','')):raw.replaceAll(',','');return Number(normalized.replace(/[^0-9.-]/g,''));}
export function parseDate(value:string){const raw=value.trim();const validISO=(date:string)=>{const parsed=new Date(`${date}T12:00:00Z`);return !Number.isNaN(parsed.getTime())&&parsed.toISOString().slice(0,10)===date?date:'';};if(/^\d{4}-\d{2}-\d{2}/.test(raw))return validISO(raw.slice(0,10));const dmy=raw.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})/);if(dmy)return validISO(`${dmy[3]}-${dmy[2].padStart(2,'0')}-${dmy[1].padStart(2,'0')}`);const parsed=new Date(raw);if(!Number.isNaN(parsed.getTime()))return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(parsed);return '';}
export const normalizedUsername=(value:string)=>value.replace(/^@/,'').trim().toLowerCase();
export function issue(row:number,field:string,sourceValue:string,severity:ImportIssue['severity'],message:string,suggestedAction:string):ImportIssue{return {row,field,sourceValue,severity,message,suggestedAction};}
