import {parseShopeeRow,detectShopeeMapping,shopeeFields} from './shopee.ts';
import {parseTikTokRow,detectTikTokMapping,tiktokFields} from './tiktok.ts';
import type {CanonicalRow,ImportIssue,RawRow} from './shared.ts';
export type {RawRow,ImportIssue,CanonicalRow} from './shared.ts';
export const mappings={TikTok:tiktokFields,Shopee:shopeeFields};
export const sourceSemantics={TikTok:'Payment Amount from TikTok Payment Order',Shopee:'Purchase Value less Refund Amount from Shopee Payment Order'};
export function detectMapping(headers:string[],market:'TikTok'|'Shopee'){return market==='TikTok'?detectTikTokMapping(headers):detectShopeeMapping(headers);}
export function parseCSV(text:string):RawRow[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Unclosed quoted field in CSV.');if(cell||row.length){row.push(cell);if(row.some(v=>v.trim()))rows.push(row);}if(rows.length<2)throw Error('The file must have a header and at least one data row.');const headers=rows.shift()!.map(v=>v.replace(/^\uFEFF/,'').trim());if(headers.some(h=>!h)||new Set(headers).size!==headers.length)throw Error('Column headers must be non-empty and unique.');if(rows.length>50000)throw Error('Maximum 50,000 rows per import.');return rows.map((r,i)=>{if(r.length!==headers.length)throw Error(`Row ${i+2} has ${r.length} fields; expected ${headers.length}.`);return Object.fromEntries(headers.map((h,j)=>[h,r[j].trim()]));});}
export function validateRows(rows:RawRow[],mapping:Record<string,string>,market:'TikTok'|'Shopee'){
 const issues:ImportIssue[]=[],valid:CanonicalRow[]=[],seen=new Set<string>();
 for(const field of mappings[market])if(field.required&&!mapping[field.key])issues.push({row:1,field:field.key,sourceValue:'',severity:'ERROR',message:`Map the required ${field.label} column.`,suggestedAction:'Choose a source column.'});
 if(issues.length)return {errors:issues.map(i=>i.message),warnings:[],issues,valid,skipped:0};
 let skipped=0;
 rows.forEach((row,index)=>{const parsed=market==='TikTok'?parseTikTokRow(row,mapping,index+2):parseShopeeRow(row,mapping,index+2);issues.push(...parsed.issues);const key=parsed.value.order_id?[parsed.value.order_id,parsed.value.source_product_id,parsed.value.source_item_id].join('|'):[parsed.value.date,parsed.value.username.toLowerCase(),parsed.value.source_product_id,parsed.value.source_item_id,parsed.value.campaign_id].join('|');if(seen.has(key))issues.push({row:index+2,field:'order_id',sourceValue:parsed.value.order_id,severity:'ERROR',message:parsed.value.order_id?'Duplicate payment order item in this file.':'Duplicate account/date/product row in this file.',suggestedAction:'Remove the duplicate transaction item.'});seen.add(key);const rowHasError=issues.some(i=>i.row===index+2&&i.severity==='ERROR');if(!rowHasError&&parsed.include)valid.push({...parsed.value,source_row_number:index+2});else skipped++;});
 const errors=issues.filter(i=>i.severity==='ERROR').map(i=>`Row ${i.row}: ${i.message}`),warnings=issues.filter(i=>i.severity==='WARNING').map(i=>`Row ${i.row}: ${i.message}`);return {errors,warnings,issues,valid,skipped};
}
