-- AffiliateOS schema v0.1. Apply once to a new Supabase project.
create extension if not exists pgcrypto;
create table public.workspaces(id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, workspace_id uuid not null references public.workspaces(id), name text not null, email text, role text not null default 'Viewer' check(role in ('Admin','Affiliate Manager','Analyst','Viewer')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create function public.current_workspace() returns uuid language sql stable security definer set search_path = '' as $$ select workspace_id from public.profiles where id=auth.uid() $$;
create function public.current_role() returns text language sql stable security definer set search_path = '' as $$ select role from public.profiles where id=auth.uid() $$;
revoke all on function public.current_workspace(), public.current_role() from public;
grant execute on function public.current_workspace(), public.current_role() to authenticated;
create table public.clients(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), name text not null check(length(trim(name))>0), industry text, owner text, status text not null default 'Active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.brands(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), name text not null, client_id uuid not null, category text, status text not null default 'Active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.products(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), name text not null, sku text not null, brand_id uuid not null, category text, status text not null default 'Active', image_path text, unique(workspace_id,sku), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.campaigns(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), name text not null, brand_id uuid not null, marketplace text not null check(marketplace in ('TikTok','Shopee','Multi-platform')), objective text, start_date date not null, end_date date not null, target_gmv numeric(18,2) default 0 check(target_gmv>=0), target_orders integer default 0 check(target_orders>=0), owner text, status text not null default 'Draft', check(end_date>=start_date), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.creators(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), name text not null, category text, email text, tags text, notes text, last_activity date, status text not null default 'Active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.creator_tags(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), creator_id uuid not null, label text not null, unique(workspace_id,creator_id,label), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.campaign_products(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), campaign_id uuid not null, product_id uuid not null, unique(workspace_id,campaign_id,product_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.campaign_creators(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), campaign_id uuid not null, creator_id uuid not null, status text default 'Active', unique(workspace_id,campaign_id,creator_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.import_jobs(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), marketplace text not null check(marketplace in ('TikTok','Shopee')), original_filename text not null, uploaded_by uuid not null references auth.users(id), status text not null default 'Ready for review', row_count integer not null default 0, successful_rows integer not null default 0, failed_rows integer not null default 0, mapping jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.import_files(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), import_job_id uuid not null, storage_path text not null, original_filename text not null, size_bytes bigint not null, mime_type text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.import_column_mappings(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), import_job_id uuid not null, marketplace text not null check(marketplace in ('TikTok','Shopee')), mapping jsonb not null, schema_version text not null default '0.1', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.raw_import_rows(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), import_job_id uuid not null, row_number integer not null, payload jsonb not null, unique(workspace_id,import_job_id,row_number), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.import_errors(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), import_job_id uuid not null, row_number integer, message text not null, severity text not null default 'error', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.tasks(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), name text not null, client_id uuid, campaign_id uuid, creator_id uuid, due_date date not null, priority text default 'Medium' check(priority in ('Low','Medium','High','Urgent')), owner text, status text default 'To Do' check(status in ('To Do','In Progress','Done')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.reports(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), name text not null, client_id uuid, campaign_id uuid, marketplace text check(marketplace in ('TikTok','Shopee','Multi-platform')), period_start date, period_end date, created_by uuid references auth.users(id), status text default 'Draft', file_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.activity_logs(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), user_id uuid references auth.users(id), actor_name text, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.tiktok_accounts(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), creator_id uuid not null, username text not null, display_name text, profile_url text, followers bigint not null default 0 check(followers>=0), status text default 'Active', unique(workspace_id,username), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.tiktok_product_mappings(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), product_id uuid not null, tiktok_product_id text not null, unique(workspace_id,product_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.tiktok_performance_daily(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), date date not null, account_id uuid not null, campaign_id uuid not null, product_id uuid, gmv numeric(18,2) not null default 0 check(gmv>=0), orders integer not null default 0 check(orders>=0), units_sold integer not null default 0 check(units_sold>=0), commission numeric(18,2) not null default 0 check(commission>=0), source_import_id uuid, video_count integer default 0 check(video_count>=0), live_count integer default 0 check(live_count>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.shopee_accounts(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), creator_id uuid not null, username text not null, display_name text, profile_url text, followers bigint not null default 0 check(followers>=0), status text default 'Active', unique(workspace_id,username), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.shopee_product_mappings(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), product_id uuid not null, shopee_item_id text not null, unique(workspace_id,product_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.shopee_performance_daily(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), date date not null, account_id uuid not null, campaign_id uuid not null, product_id uuid, gmv numeric(18,2) not null default 0 check(gmv>=0), orders integer not null default 0 check(orders>=0), units_sold integer not null default 0 check(units_sold>=0), commission numeric(18,2) not null default 0 check(commission>=0), source_import_id uuid, clicks integer default 0 check(clicks>=0), conversion_rate numeric(8,6) default 0 check(conversion_rate between 0 and 1), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.tiktok_content(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), account_id uuid not null, campaign_id uuid, product_id uuid, source_import_id uuid, content_url text, content_type text check(content_type in ('Video','Live')), published_at timestamptz, title text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.shopee_affiliate_activity(id uuid primary key default gen_random_uuid(), workspace_id uuid not null default public.current_workspace() references public.workspaces(id), account_id uuid not null, campaign_id uuid, product_id uuid, source_import_id uuid, date date not null, clicks integer default 0, orders integer default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create index on public.clients(workspace_id);
alter table public.brands add foreign key(workspace_id,client_id) references public.clients(workspace_id,id);
create index on public.brands(workspace_id);
alter table public.products add foreign key(workspace_id,brand_id) references public.brands(workspace_id,id);
create index on public.products(workspace_id);
alter table public.campaigns add foreign key(workspace_id,brand_id) references public.brands(workspace_id,id);
create index on public.campaigns(workspace_id);
create index on public.creators(workspace_id);
alter table public.creator_tags add foreign key(workspace_id,creator_id) references public.creators(workspace_id,id);
create index on public.creator_tags(workspace_id);
alter table public.campaign_products add foreign key(workspace_id,campaign_id) references public.campaigns(workspace_id,id);
alter table public.campaign_products add foreign key(workspace_id,product_id) references public.products(workspace_id,id);
create index on public.campaign_products(workspace_id);
alter table public.campaign_creators add foreign key(workspace_id,creator_id) references public.creators(workspace_id,id);
alter table public.campaign_creators add foreign key(workspace_id,campaign_id) references public.campaigns(workspace_id,id);
create index on public.campaign_creators(workspace_id);
create index on public.import_jobs(workspace_id);
alter table public.import_files add foreign key(workspace_id,import_job_id) references public.import_jobs(workspace_id,id);
create index on public.import_files(workspace_id);
alter table public.import_column_mappings add foreign key(workspace_id,import_job_id) references public.import_jobs(workspace_id,id);
create index on public.import_column_mappings(workspace_id);
alter table public.raw_import_rows add foreign key(workspace_id,import_job_id) references public.import_jobs(workspace_id,id);
create index on public.raw_import_rows(workspace_id);
alter table public.import_errors add foreign key(workspace_id,import_job_id) references public.import_jobs(workspace_id,id);
create index on public.import_errors(workspace_id);
alter table public.tasks add foreign key(workspace_id,client_id) references public.clients(workspace_id,id);
alter table public.tasks add foreign key(workspace_id,creator_id) references public.creators(workspace_id,id);
alter table public.tasks add foreign key(workspace_id,campaign_id) references public.campaigns(workspace_id,id);
create index on public.tasks(workspace_id);
alter table public.reports add foreign key(workspace_id,client_id) references public.clients(workspace_id,id);
alter table public.reports add foreign key(workspace_id,campaign_id) references public.campaigns(workspace_id,id);
create index on public.reports(workspace_id);
create index on public.activity_logs(workspace_id);
alter table public.tiktok_accounts add foreign key(workspace_id,creator_id) references public.creators(workspace_id,id);
create index on public.tiktok_accounts(workspace_id);
alter table public.tiktok_product_mappings add foreign key(workspace_id,product_id) references public.products(workspace_id,id);
create index on public.tiktok_product_mappings(workspace_id);
alter table public.tiktok_performance_daily add foreign key(workspace_id,campaign_id) references public.campaigns(workspace_id,id);
alter table public.tiktok_performance_daily add foreign key(workspace_id,product_id) references public.products(workspace_id,id);
alter table public.tiktok_performance_daily add foreign key(workspace_id,source_import_id) references public.import_jobs(workspace_id,id);
alter table public.tiktok_performance_daily add foreign key(workspace_id,account_id) references public.tiktok_accounts(workspace_id,id);
create index on public.tiktok_performance_daily(workspace_id);
create index on public.tiktok_performance_daily(workspace_id,date,campaign_id);
create unique index on public.tiktok_performance_daily(workspace_id,date,account_id,campaign_id,coalesce(product_id,'00000000-0000-0000-0000-000000000000'::uuid));
alter table public.shopee_accounts add foreign key(workspace_id,creator_id) references public.creators(workspace_id,id);
create index on public.shopee_accounts(workspace_id);
alter table public.shopee_product_mappings add foreign key(workspace_id,product_id) references public.products(workspace_id,id);
create index on public.shopee_product_mappings(workspace_id);
alter table public.shopee_performance_daily add foreign key(workspace_id,campaign_id) references public.campaigns(workspace_id,id);
alter table public.shopee_performance_daily add foreign key(workspace_id,product_id) references public.products(workspace_id,id);
alter table public.shopee_performance_daily add foreign key(workspace_id,source_import_id) references public.import_jobs(workspace_id,id);
alter table public.shopee_performance_daily add foreign key(workspace_id,account_id) references public.shopee_accounts(workspace_id,id);
create index on public.shopee_performance_daily(workspace_id);
create index on public.shopee_performance_daily(workspace_id,date,campaign_id);
create unique index on public.shopee_performance_daily(workspace_id,date,account_id,campaign_id,coalesce(product_id,'00000000-0000-0000-0000-000000000000'::uuid));
alter table public.tiktok_content add foreign key(workspace_id,campaign_id) references public.campaigns(workspace_id,id);
alter table public.tiktok_content add foreign key(workspace_id,product_id) references public.products(workspace_id,id);
alter table public.tiktok_content add foreign key(workspace_id,source_import_id) references public.import_jobs(workspace_id,id);
alter table public.tiktok_content add foreign key(workspace_id,account_id) references public.tiktok_accounts(workspace_id,id);
create index on public.tiktok_content(workspace_id);
alter table public.shopee_affiliate_activity add foreign key(workspace_id,campaign_id) references public.campaigns(workspace_id,id);
alter table public.shopee_affiliate_activity add foreign key(workspace_id,product_id) references public.products(workspace_id,id);
alter table public.shopee_affiliate_activity add foreign key(workspace_id,source_import_id) references public.import_jobs(workspace_id,id);
alter table public.shopee_affiliate_activity add foreign key(workspace_id,account_id) references public.shopee_accounts(workspace_id,id);
create index on public.shopee_affiliate_activity(workspace_id);

-- App roles are enforced in PostgreSQL as well as route handlers.
alter table public.workspaces enable row level security;
alter table public.profiles enable row level security;
create policy workspace_read on public.workspaces for select to authenticated using(id=public.current_workspace());
create policy profile_read on public.profiles for select to authenticated using(workspace_id=public.current_workspace());
create policy profile_edit_self on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid() and workspace_id=public.current_workspace());
revoke all on public.profiles,public.workspaces from anon,authenticated;
grant select on public.profiles,public.workspaces to authenticated;
grant update(name) on public.profiles to authenticated;
alter table public.clients enable row level security;
revoke all on public.clients from anon,authenticated;
grant select on public.clients to authenticated;
create policy workspace_read on public.clients for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.clients to authenticated;
create policy workspace_insert on public.clients for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.clients for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.clients for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
alter table public.brands enable row level security;
revoke all on public.brands from anon,authenticated;
grant select on public.brands to authenticated;
create policy workspace_read on public.brands for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.brands to authenticated;
create policy workspace_insert on public.brands for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.brands for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.brands for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
alter table public.products enable row level security;
revoke all on public.products from anon,authenticated;
grant select on public.products to authenticated;
create policy workspace_read on public.products for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.products to authenticated;
create policy workspace_insert on public.products for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.products for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.products for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
alter table public.campaigns enable row level security;
revoke all on public.campaigns from anon,authenticated;
grant select on public.campaigns to authenticated;
create policy workspace_read on public.campaigns for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.campaigns to authenticated;
create policy workspace_insert on public.campaigns for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_update on public.campaigns for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_delete on public.campaigns for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.creators enable row level security;
revoke all on public.creators from anon,authenticated;
grant select on public.creators to authenticated;
create policy workspace_read on public.creators for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.creators to authenticated;
create policy workspace_insert on public.creators for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_update on public.creators for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_delete on public.creators for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.creator_tags enable row level security;
revoke all on public.creator_tags from anon,authenticated;
grant select on public.creator_tags to authenticated;
create policy workspace_read on public.creator_tags for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.creator_tags to authenticated;
create policy workspace_insert on public.creator_tags for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_update on public.creator_tags for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_delete on public.creator_tags for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.campaign_products enable row level security;
revoke all on public.campaign_products from anon,authenticated;
grant select on public.campaign_products to authenticated;
create policy workspace_read on public.campaign_products for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.campaign_products to authenticated;
create policy workspace_insert on public.campaign_products for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_update on public.campaign_products for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_delete on public.campaign_products for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.campaign_creators enable row level security;
revoke all on public.campaign_creators from anon,authenticated;
grant select on public.campaign_creators to authenticated;
create policy workspace_read on public.campaign_creators for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.campaign_creators to authenticated;
create policy workspace_insert on public.campaign_creators for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_update on public.campaign_creators for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_delete on public.campaign_creators for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.import_jobs enable row level security;
revoke all on public.import_jobs from anon,authenticated;
grant select on public.import_jobs to authenticated;
create policy workspace_read on public.import_jobs for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.import_jobs to authenticated;
create policy workspace_insert on public.import_jobs for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_update on public.import_jobs for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_delete on public.import_jobs for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.import_files enable row level security;
revoke all on public.import_files from anon,authenticated;
grant select on public.import_files to authenticated;
create policy workspace_read on public.import_files for select to authenticated using(workspace_id=public.current_workspace());
grant insert on public.import_files to authenticated;
create policy workspace_insert on public.import_files for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.import_column_mappings enable row level security;
revoke all on public.import_column_mappings from anon,authenticated;
grant select on public.import_column_mappings to authenticated;
create policy workspace_read on public.import_column_mappings for select to authenticated using(workspace_id=public.current_workspace());
grant insert on public.import_column_mappings to authenticated;
create policy workspace_insert on public.import_column_mappings for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.raw_import_rows enable row level security;
revoke all on public.raw_import_rows from anon,authenticated;
grant select on public.raw_import_rows to authenticated;
create policy workspace_read on public.raw_import_rows for select to authenticated using(workspace_id=public.current_workspace());
grant insert on public.raw_import_rows to authenticated;
create policy workspace_insert on public.raw_import_rows for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.import_errors enable row level security;
revoke all on public.import_errors from anon,authenticated;
grant select on public.import_errors to authenticated;
create policy workspace_read on public.import_errors for select to authenticated using(workspace_id=public.current_workspace());
grant insert on public.import_errors to authenticated;
create policy workspace_insert on public.import_errors for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.tasks enable row level security;
revoke all on public.tasks from anon,authenticated;
grant select on public.tasks to authenticated;
create policy workspace_read on public.tasks for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.tasks to authenticated;
create policy workspace_insert on public.tasks for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_update on public.tasks for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_delete on public.tasks for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.reports enable row level security;
revoke all on public.reports from anon,authenticated;
grant select on public.reports to authenticated;
create policy workspace_read on public.reports for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.reports to authenticated;
create policy workspace_insert on public.reports for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.reports for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.reports for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
alter table public.activity_logs enable row level security;
revoke all on public.activity_logs from anon,authenticated;
grant select on public.activity_logs to authenticated;
create policy workspace_read on public.activity_logs for select to authenticated using(workspace_id=public.current_workspace());
alter table public.tiktok_accounts enable row level security;
revoke all on public.tiktok_accounts from anon,authenticated;
grant select on public.tiktok_accounts to authenticated;
create policy workspace_read on public.tiktok_accounts for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.tiktok_accounts to authenticated;
create policy workspace_insert on public.tiktok_accounts for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_update on public.tiktok_accounts for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_delete on public.tiktok_accounts for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.tiktok_product_mappings enable row level security;
revoke all on public.tiktok_product_mappings from anon,authenticated;
grant select on public.tiktok_product_mappings to authenticated;
create policy workspace_read on public.tiktok_product_mappings for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.tiktok_product_mappings to authenticated;
create policy workspace_insert on public.tiktok_product_mappings for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.tiktok_product_mappings for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.tiktok_product_mappings for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
alter table public.tiktok_performance_daily enable row level security;
revoke all on public.tiktok_performance_daily from anon,authenticated;
grant select on public.tiktok_performance_daily to authenticated;
create policy workspace_read on public.tiktok_performance_daily for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.tiktok_performance_daily to authenticated;
create policy workspace_insert on public.tiktok_performance_daily for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.tiktok_performance_daily for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.tiktok_performance_daily for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
alter table public.shopee_accounts enable row level security;
revoke all on public.shopee_accounts from anon,authenticated;
grant select on public.shopee_accounts to authenticated;
create policy workspace_read on public.shopee_accounts for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.shopee_accounts to authenticated;
create policy workspace_insert on public.shopee_accounts for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_update on public.shopee_accounts for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_delete on public.shopee_accounts for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin','Affiliate Manager'));
alter table public.shopee_product_mappings enable row level security;
revoke all on public.shopee_product_mappings from anon,authenticated;
grant select on public.shopee_product_mappings to authenticated;
create policy workspace_read on public.shopee_product_mappings for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.shopee_product_mappings to authenticated;
create policy workspace_insert on public.shopee_product_mappings for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.shopee_product_mappings for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.shopee_product_mappings for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
alter table public.shopee_performance_daily enable row level security;
revoke all on public.shopee_performance_daily from anon,authenticated;
grant select on public.shopee_performance_daily to authenticated;
create policy workspace_read on public.shopee_performance_daily for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.shopee_performance_daily to authenticated;
create policy workspace_insert on public.shopee_performance_daily for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.shopee_performance_daily for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.shopee_performance_daily for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
alter table public.tiktok_content enable row level security;
revoke all on public.tiktok_content from anon,authenticated;
grant select on public.tiktok_content to authenticated;
create policy workspace_read on public.tiktok_content for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.tiktok_content to authenticated;
create policy workspace_insert on public.tiktok_content for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.tiktok_content for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.tiktok_content for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
alter table public.shopee_affiliate_activity enable row level security;
revoke all on public.shopee_affiliate_activity from anon,authenticated;
grant select on public.shopee_affiliate_activity to authenticated;
create policy workspace_read on public.shopee_affiliate_activity for select to authenticated using(workspace_id=public.current_workspace());
grant insert,update,delete on public.shopee_affiliate_activity to authenticated;
create policy workspace_insert on public.shopee_affiliate_activity for insert to authenticated with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_update on public.shopee_affiliate_activity for update to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin')) with check(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));
create policy workspace_delete on public.shopee_affiliate_activity for delete to authenticated using(workspace_id=public.current_workspace() and public.current_role() in ('Admin'));

create function public.touch_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end $$;
create function public.audit_record() returns trigger language plpgsql security definer set search_path='' as $$
declare r jsonb; actor text;
begin
  if TG_OP='DELETE' then r=to_jsonb(old); else r=to_jsonb(new); end if;
  select name into actor from public.profiles where id=auth.uid();
  insert into public.activity_logs(workspace_id,user_id,actor_name,action,entity_type,entity_id,metadata)
  values((r->>'workspace_id')::uuid,auth.uid(),coalesce(actor,'System'),coalesce(r->>'name',TG_TABLE_NAME)||' '||lower(TG_OP),TG_TABLE_NAME,(r->>'id')::uuid,jsonb_build_object('operation',TG_OP));
  if TG_OP='DELETE' then return old; else return new; end if;
end $$;
create trigger touch_updated_at before update on public.clients for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.clients for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.brands for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.brands for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.products for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.products for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.campaigns for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.campaigns for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.creators for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.creators for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.creator_tags for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.campaign_products for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.campaign_creators for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.campaign_creators for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.import_jobs for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.import_jobs for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.import_files for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.import_column_mappings for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.raw_import_rows for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.import_errors for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.tasks for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.tasks for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.reports for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.activity_logs for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.tiktok_accounts for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.tiktok_accounts for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.tiktok_product_mappings for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.tiktok_performance_daily for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.shopee_accounts for each row execute function public.touch_updated_at();
create trigger audit_change after insert or update or delete on public.shopee_accounts for each row execute function public.audit_record();
create trigger touch_updated_at before update on public.shopee_product_mappings for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.shopee_performance_daily for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.tiktok_content for each row execute function public.touch_updated_at();
create trigger touch_updated_at before update on public.shopee_affiliate_activity for each row execute function public.touch_updated_at();

-- Raw imports are staged atomically; no analytics table is written here.
create function public.stage_import(job jsonb, file_metadata jsonb, raw_rows jsonb, validation_errors jsonb) returns uuid language plpgsql security invoker set search_path='' as $$
declare jid uuid := (job->>'id')::uuid; wid uuid := public.current_workspace();
begin
  if public.current_role() not in ('Admin','Affiliate Manager') then raise exception 'Insufficient access'; end if;
  if jsonb_array_length(raw_rows)>10000 then raise exception 'Row limit exceeded'; end if;
  insert into public.import_jobs(id,workspace_id,marketplace,original_filename,uploaded_by,status,row_count,successful_rows,failed_rows,mapping)
  values(jid,wid,job->>'marketplace',job->>'filename',auth.uid(),job->>'status',jsonb_array_length(raw_rows),0,(job->>'failed_rows')::integer,job->'mapping');
  insert into public.import_files(workspace_id,import_job_id,storage_path,original_filename,size_bytes,mime_type)
  values(wid,jid,file_metadata->>'path',job->>'filename',(file_metadata->>'size')::bigint,file_metadata->>'type');
  insert into public.import_column_mappings(workspace_id,import_job_id,marketplace,mapping) values(wid,jid,job->>'marketplace',job->'mapping');
  insert into public.raw_import_rows(workspace_id,import_job_id,row_number,payload) select wid,jid,ordinality::integer+1,value from jsonb_array_elements(raw_rows) with ordinality;
  insert into public.import_errors(workspace_id,import_job_id,message) select wid,jid,value #>> '{}' from jsonb_array_elements(validation_errors);
  return jid;
end $$;
revoke all on function public.stage_import(jsonb,jsonb,jsonb,jsonb) from public;
grant execute on function public.stage_import(jsonb,jsonb,jsonb,jsonb) to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('workspace-files','workspace-files',false,5242880,array['text/csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/octet-stream']) on conflict(id) do nothing;
create policy workspace_files_read on storage.objects for select to authenticated using(bucket_id='workspace-files' and (storage.foldername(name))[1]=public.current_workspace()::text);
create policy workspace_files_insert on storage.objects for insert to authenticated with check(bucket_id='workspace-files' and (storage.foldername(name))[1]=public.current_workspace()::text and public.current_role() in ('Admin','Affiliate Manager'));
create policy workspace_files_delete on storage.objects for delete to authenticated using(bucket_id='workspace-files' and (storage.foldername(name))[1]=public.current_workspace()::text and public.current_role() in ('Admin','Affiliate Manager'));

-- Prevent cross-marketplace provenance or campaign attribution.
create function public.validate_marketplace_source() returns trigger language plpgsql set search_path='' as $$
declare expected text; source_market text; campaign_market text;
begin
  expected := case when TG_TABLE_NAME like 'tiktok_%' then 'TikTok' else 'Shopee' end;
  if new.source_import_id is not null then
    select marketplace into source_market from public.import_jobs where id=new.source_import_id and workspace_id=new.workspace_id;
    if source_market is distinct from expected then raise exception 'Source import marketplace does not match performance table'; end if;
  end if;
  select marketplace into campaign_market from public.campaigns where id=new.campaign_id and workspace_id=new.workspace_id;
  if campaign_market not in (expected,'Multi-platform') then raise exception 'Campaign marketplace does not match performance table'; end if;
  return new;
end $$;
create trigger validate_market before insert or update on public.tiktok_performance_daily for each row execute function public.validate_marketplace_source();
create trigger validate_market before insert or update on public.shopee_performance_daily for each row execute function public.validate_marketplace_source();
create unique index tiktok_username_case_insensitive on public.tiktok_accounts(workspace_id,lower(username));
create unique index shopee_username_case_insensitive on public.shopee_accounts(workspace_id,lower(username));
