import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import JSZip from 'jszip';import type { ReportTemplate } from './templates.ts';import { snapshotMetric,type FrozenReportSnapshot } from './snapshot.ts';
const source=()=>path.join(process.cwd(),'report-templates/private/anymind-haleon-weekly-v1.pptx');
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const money=(v:number|null)=>v===null?'Source unavailable':new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(v);
const pct=(v:number|null)=>v===null?'Source unavailable':`${(v*100).toFixed(2)}%`;
function replaceTexts(xml:string,map:Record<number,string>){let i=-1;return xml.replace(/<a:t(\s[^>]*)?>([\s\S]*?)<\/a:t>/g,(_all,attrs='')=>{i++;return `<a:t${attrs}>${esc(map[i]??'')}</a:t>`;});}
function removeNonLogoPictures(xml:string){return xml.replace(/<p:pic>[\s\S]*?<\/p:pic>/g,block=>/r:embed="rId3"/.test(block)?block:'');}
async function pruneUnusedTemplateParts(zip:JSZip){
 for(const name of Object.keys(zip.files)){
  const unusedSlide=/^ppt\/slides\/slide(?!21\.xml$)\d+\.xml$/.test(name);
  const unusedSlideRels=/^ppt\/slides\/_rels\/slide(?!21\.xml\.rels$)\d+\.xml\.rels$/.test(name);
  const unusedMedia=name.startsWith('ppt/media/')&&!/^ppt\/media\/image(4|5|7)\.png$/.test(name);
  const unusedFolder=/^ppt\/(notesSlides|charts|embeddings|diagrams|comments)\//.test(name)||name==='ppt/commentAuthors.xml';
  if(unusedSlide||unusedSlideRels||unusedMedia||unusedFolder)zip.remove(name);
 }
 const relsFile=zip.file('ppt/_rels/presentation.xml.rels');if(relsFile){const rels=await relsFile.async('string');zip.file('ppt/_rels/presentation.xml.rels',rels.replace(/<Relationship[^>]*Type="[^"]*\/slide"[^>]*Target="slides\/slide(?!21\.xml)[^"]+"[^>]*\/>/g,'').replace(/<Relationship[^>]*Type="[^"]*\/commentAuthors"[^>]*\/>/g,''));}
}
export async function buildAnyMindPowerPoint(input:{reportName:string;snapshot:FrozenReportSnapshot;template:ReportTemplate;finalizedAt:string}){const original=await fs.readFile(source()),hash=crypto.createHash('sha256').update(original).digest('hex');if(hash!==input.template.sourceHash)throw Error('PowerPoint template integrity check failed.');const zip=await JSZip.loadAsync(original),s=input.snapshot,src=s.sources?.[0];
 const slide16=await zip.file('ppt/slides/slide16.xml')!.async('string'),slide21=await zip.file('ppt/slides/slide21.xml')!.async('string');
 const roi=snapshotMetric(s,'roi');
 const map16:Record<number,string>={1:`Weekly Review ${s.period.start} to ${s.period.end}`,2:`${s.marketplace} Performance `,3:'(Snapshot)',4:input.reportName,7:'Key Highlights',8:'What Went Well:',9:` ${String(s.narrative?.what_went_well||'No narrative added.')}`,10:'Issues / Risks:',11:` ${String(s.narrative?.issues||'No issues recorded.')}`,12:'Next Action:',13:` ${String(s.narrative?.next_action||'No next action recorded.')}`,18:'Metric',19:'Affiliate GMV',20:'Commission',21:'ROI',22:'Cost Ratio',23:'Affiliates with Sales',24:'Orders',25:'Units',26:'Snapshot',27:money(snapshotMetric(s,'affiliateGmv')),28:money(snapshotMetric(s,'commission')),29:roi===null?'Source unavailable':roi.toFixed(2),30:pct(snapshotMetric(s,'costRatio')),31:money(snapshotMetric(s,'affiliatesWithSales')),32:money(snapshotMetric(s,'orders')),33:'Period',34:`${s.period.start} to ${s.period.end}`,35:'Finalized',36:input.finalizedAt.slice(0,10),37:'Marketplace',38:s.marketplace,39:money(snapshotMetric(s,'quantity')),40:'Status',41:'Final',49:'Source Lineage',50:'Marketplace',51:'Source',52:'Period start',53:'Period end',54:'Status',55:'Metric',56:'Snapshot',60:src?.marketplace?String(src.marketplace):'Source unavailable',61:src?.filename?String(src.filename):'Source unavailable',62:src?.period_start?String(src.period_start):'—',63:src?.period_end?String(src.period_end):'—',64:src?.status?String(src.status):'—',65:src?.sales_metric?String(src.sales_metric):'Processed sales'};
 const map21:Record<number,string>={1:`Weekly Review ${s.period.start} to ${s.period.end}`,2:`${s.marketplace} Performance `,3:'(Snapshot)',6:'Manual Narratives',7:'Affiliate GMV / Commission',8:`Rp${money(snapshotMetric(s,'affiliateGmv'))} / Rp${money(snapshotMetric(s,'commission'))}`,10:'Orders / Units',11:`${money(snapshotMetric(s,'orders'))} / ${money(snapshotMetric(s,'quantity'))}`,12:`ROI ${roi===null?'—':roi.toFixed(2)} · Cost ratio ${pct(snapshotMetric(s,'costRatio'))} · ${money(snapshotMetric(s,'affiliatesWithSales'))} affiliate(s) with sales`,13:'What Went Well:',14:' ',15:String(s.narrative?.what_went_well||'No narrative added.'),17:'Issues / Risks:',18:' ',19:String(s.narrative?.issues||'No issues recorded.'),23:'Next Action:',24:' ',25:String(s.narrative?.next_action||'No next action recorded.'),26:''};
 zip.file('ppt/slides/slide16.xml',replaceTexts(removeNonLogoPictures(slide16),map16));zip.file('ppt/slides/slide21.xml',replaceTexts(removeNonLogoPictures(slide21),map21));
 const slide21Rels=await zip.file('ppt/slides/_rels/slide21.xml.rels')!.async('string');zip.file('ppt/slides/_rels/slide21.xml.rels',slide21Rels.replace(/<Relationship[^>]*Id="rId(2|4|5)"[^>]*\/>/g,''));
 const rels=await zip.file('ppt/_rels/presentation.xml.rels')!.async('string'),keep=new Set<string>();for(const n of [21]){const match=rels.match(new RegExp(`<Relationship[^>]*Id="([^"]+)"[^>]*Target="slides/slide${n}\\.xml"[^>]*/>`));if(match)keep.add(match[1]);}let pres=await zip.file('ppt/presentation.xml')!.async('string');pres=pres.replace(/<p:sldIdLst>[\s\S]*?<\/p:sldIdLst>/,block=>`<p:sldIdLst>${[...block.matchAll(/<p:sldId[^>]*r:id="([^"]+)"[^>]*\/>/g)].filter(x=>keep.has(x[1])).map(x=>x[0]).join('')}</p:sldIdLst>`);zip.file('ppt/presentation.xml',pres);
 const coreFile=zip.file('docProps/core.xml');if(coreFile){const core=await coreFile.async('string');zip.file('docProps/core.xml',core.replace(/<dc:title>[\s\S]*?<\/dc:title>/,`<dc:title>${esc(input.reportName)}</dc:title>`));}
 const appFile=zip.file('docProps/app.xml');if(appFile){const app=await appFile.async('string');zip.file('docProps/app.xml',app.replace(/<Slides>\d+<\/Slides>/,'<Slides>1</Slides>').replace(/<Notes>\d+<\/Notes>/,'<Notes>0</Notes>'));}
 await pruneUnusedTemplateParts(zip);
 const contentTypes=await zip.file('[Content_Types].xml')!.async('string');zip.file('[Content_Types].xml',contentTypes.replace(/<Override\b[^>]*\/>/g,tag=>{const part=tag.match(/PartName="([^"]+)"/)?.[1]||'';const removedSlide=/^\/ppt\/slides\/slide(?!21\.xml$)\d+\.xml$/.test(part);const removedFolder=/^\/ppt\/(notesSlides|charts|embeddings|diagrams|comments)\//.test(part)||part==='/ppt/commentAuthors.xml';return removedSlide||removedFolder?'':tag;}));
 return Buffer.from(await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE'}));}
